-- ===========================================================================
-- 0000_init — the whole Phase 1 schema, constraints included.
--
-- Generated by drizzle-kit from packages/db/src/schema, then annotated by hand:
-- the comments below are the only edits, and they are here because this file,
-- not the TypeScript, is what a reviewer who does not know Drizzle will read.
-- Regenerating this file would drop them; it is already applied, so it will not
-- be regenerated — later changes arrive as 0001, 0002, ...
--
-- Every correctness constraint ships in this first migration, including the
-- ones no Phase 1 code exercises yet (technical-considerations §1, assumption
-- A2). Unique indexes cost nothing to add now and are the entire correctness
-- story later; Phase 2 adds the *behaviour* that exploits them, not the
-- constraints themselves.
--
-- Invariant markers (I1-I9) refer to context/product/architecture.md §3, and
-- the statement each one supports is quoted at the constraint in
-- packages/db/src/schema/*.ts.
--
--   I1  orders.client_request_id UNIQUE .................. one request → one order
--   I2  payment_events.event_id PRIMARY KEY .............. one event applied once
--   I3  deliveries.order_id / request_id UNIQUE .......... one order → one delivery
--   I5  supplier_requests.request_id PRIMARY KEY ......... one request → one code
--   I6  supplier_keys.claimed_by_request_id UNIQUE ....... one key → one request
--   I9  orders_status_check + guarded UPDATEs ............ final states terminal
--
-- I4 (only one worker advances an order) is `SELECT ... FOR UPDATE` on the
-- order row: a lock, so it needs no DDL. I7/I8 are the promo tables, Phase 5.
--
-- Money is integer minor units everywhere (`price_minor`, `amount_minor`).
-- There is no floating-point column in this schema.
-- ===========================================================================

-- deliveries — the issued key bound to an order. One row here is the shop's
-- definition of "this shopper has been given a key".
CREATE TABLE "deliveries" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "deliveries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" text NOT NULL,
	"code" text NOT NULL,
	"provider" text NOT NULL,
	"request_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	-- I3 — one order → at most one delivery.
	--   INSERT INTO deliveries (order_id, code, provider, request_id)
	--   VALUES ($1, $2, $3, $4) ON CONFLICT (order_id) DO NOTHING RETURNING *;
	--   -- 0 rows => already delivered; keep the existing key, do NOT issue again.
	-- Without it, two concurrent workers both see "not delivered" and both issue.
	CONSTRAINT "deliveries_order_id_key" UNIQUE("order_id"),
	-- I3 — and one supplier request cannot be bound to two orders.
	CONSTRAINT "deliveries_request_id_key" UNIQUE("request_id")
);
--> statement-breakpoint
-- issuance_attempts — one row per supplier call; the ledger the Phase 3 retry
-- policy reasons over (`unknown` = timeout, retry the SAME request_id).
CREATE TABLE "issuance_attempts" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "issuance_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"request_id" text NOT NULL,
	"order_id" text NOT NULL,
	"provider" text NOT NULL,
	"status" text NOT NULL,
	"code" text,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	-- request_id is derived as req_{order_id}_{provider}_{attempt}, so a retry
	-- computes the id it used before; UNIQUE keeps that retry to one row of
	-- history rather than two.
	CONSTRAINT "issuance_attempts_request_id_key" UNIQUE("request_id")
);
--> statement-breakpoint
-- orders — one row per purchase attempt, and the state machine that carries it.
-- id is `ord_` + ULID, generated by the application: a webhook may quote an
-- order id before the row exists, which a sequence could not support.
CREATE TABLE "orders" (
	"id" text PRIMARY KEY NOT NULL,
	"client_request_id" text,
	"sku" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"currency" text NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	-- I1 — one client request → one order. NULL in Phase 1 (nothing sends the
	-- Idempotency-Key header yet), populated in Phase 2; NULLs do not collide in
	-- a Postgres unique index, so unkeyed orders coexist under it.
	--   INSERT INTO orders (...) VALUES (...)
	--   ON CONFLICT (client_request_id) DO NOTHING RETURNING *;
	--   -- 0 rows => another request won; read that order back and return 200.
	-- Without it, a double-click creates two orders and two charges.
	CONSTRAINT "orders_client_request_id_key" UNIQUE("client_request_id"),
	-- I9 — the states an order may be in, in Phase 1. `delivery_failed` is
	-- Phase 3 and is deliberately absent. Terminality itself comes from the
	-- status-guarded UPDATEs:
	--   UPDATE orders SET status = $2, updated_at = now()
	--   WHERE id = $1 AND status = ANY($3) RETURNING *;
	--   -- 0 rows => not in a permitted source state; the caller does nothing,
	--   --           so a late webhook cannot resurrect a completed order.
	CONSTRAINT "orders_status_check" CHECK ("status" IN ('created', 'paid', 'delivering', 'delivered', 'payment_failed', 'out_of_stock')),
	-- Money is unsigned integer minor units (kopecks), never a float.
	CONSTRAINT "orders_amount_minor_nonnegative" CHECK ("amount_minor" >= 0)
);
--> statement-breakpoint
-- payment_events — the durable webhook inbox, and the work queue that drains it.
--
-- I2 — one payment event is applied once. The provider's own event id is the
-- PRIMARY KEY, with no surrogate key beside it: the natural key *is* the
-- deduplication mechanism.
--   INSERT INTO payment_events (event_id, order_id, status, amount_minor, currency, payload)
--   VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (event_id) DO NOTHING RETURNING *;
--   -- 1 row  => first sight; process it.
--   -- 0 rows => redelivery; acknowledge 200 and stop.
--
-- ###########################################################################
-- # order_id CARRIES NO FOREIGN KEY. THAT IS DELIBERATE — DO NOT "FIX" IT.  #
-- ###########################################################################
-- architecture.md §4, "Out-of-order tolerance": an event for an order that does
-- not exist yet is stored with processed_at NULL and drained later. The missing
-- FK is what makes "webhook arrives before its order" a normal path instead of
-- an error. Add REFERENCES here and an event that arrives a few milliseconds
-- early becomes a 500, which makes the provider retry — the exact failure this
-- design exists to avoid. deliveries and issuance_attempts DO have FKs to
-- orders below; the contrast is the point.
CREATE TABLE "payment_events" (
	"event_id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	-- No CHECK on status either: it is the provider's value, and persist-first
	-- means an unrecognised status is stored and then ignored, not rejected.
	"status" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"currency" text NOT NULL,
	"payload" jsonb NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	-- NULL = pending work. This column is the queue.
	"processed_at" timestamp with time zone
);
--> statement-breakpoint
-- products — the supplied catalog (twelve items, loaded by the seed).
CREATE TABLE "products" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sku" text NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"price_minor" integer NOT NULL,
	"currency" text NOT NULL,
	"image" text,
	"purchasable" boolean DEFAULT false NOT NULL,
	-- The catalog's identity, and what lets the seed re-run via
	-- ON CONFLICT (sku) DO UPDATE.
	CONSTRAINT "products_sku_key" UNIQUE("sku"),
	CONSTRAINT "products_price_minor_nonnegative" CHECK ("price_minor" >= 0)
);
--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- SUPPLIER-SIDE TABLES — not the shop's. These belong to the simulated key
-- supplier and live here only so one `docker compose up` runs the whole
-- demonstration. The shop never selects from them: it asks for a key over HTTP
-- and believes the answer only once it has written a deliveries row of its own.
-- Sharing state with a service the shop is supposed to distrust would hand it
-- guarantees it has not earned, and would make every Phase 3 failure scenario
-- meaningless.
-- ---------------------------------------------------------------------------
CREATE TABLE "supplier_keys" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "supplier_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"claimed_by_request_id" text,
	"claimed_at" timestamp with time zone,
	-- The pool cannot hold the same code twice.
	CONSTRAINT "supplier_keys_code_key" UNIQUE("code"),
	-- I6 — one key → at most one request. NULL means unclaimed; once set it
	-- never changes.
	--   UPDATE supplier_keys SET claimed_by_request_id = $1, claimed_at = now()
	--   WHERE code = (SELECT code FROM supplier_keys
	--                 WHERE claimed_by_request_id IS NULL
	--                 ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1)
	--   RETURNING code;
	--   -- 0 rows => pool exhausted => the supplier answers out_of_stock.
	-- One statement, so there is no read-then-write window; this index is the
	-- backstop that makes selling the same key twice impossible even if that
	-- statement were written wrongly.
	CONSTRAINT "supplier_keys_claimed_by_request_id_key" UNIQUE("claimed_by_request_id")
);
--> statement-breakpoint
-- supplier_requests — the supplier's own idempotency ledger. The Phase 3
-- timeout trap rests entirely on this table.
CREATE TABLE "supplier_requests" (
	-- I5 — one supplier request → one code. Checked before any key is touched:
	--   SELECT code FROM supplier_requests WHERE request_id = $1;
	--   -- 1 row  => return that code unchanged, however often we are asked.
	--   -- 0 rows => first sight; claim a key (I6) and record the pair in the
	--   --           same transaction as the claim.
	-- Without it, a retry after a timeout issues a second key.
	"request_id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- A delivery only exists for an order the code has already read — unlike a
-- payment event, which may legitimately arrive first. Hence: FK here, none there.
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveries_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issuance_attempts" ADD CONSTRAINT "issuance_attempts_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- "Does this order still have an attempt in `unknown`?" — the question the
-- Phase 3 retry policy must answer before falling through to supplier B. Also
-- the index the foreign key above needs; Postgres does not create it itself.
CREATE INDEX "issuance_attempts_order_id_idx" ON "issuance_attempts" USING btree ("order_id");--> statement-breakpoint
-- Serves the Phase 3 admin view: paid but undelivered.
CREATE INDEX "orders_status_idx" ON "orders" USING btree ("status");--> statement-breakpoint
-- The inbox-as-queue access path. Partial, so it holds only unprocessed events
-- and stays a handful of rows however many events accumulate. Serves both the
-- targeted drain (WHERE order_id = $1 AND processed_at IS NULL) and the sweep
-- (WHERE processed_at IS NULL ORDER BY received_at FOR UPDATE SKIP LOCKED
-- LIMIT 1 — 0 rows means nothing pending, or every pending row is already held
-- by another worker).
CREATE INDEX "payment_events_unprocessed_order_idx" ON "payment_events" USING btree ("order_id") WHERE "processed_at" IS NULL;--> statement-breakpoint
-- The claim's hot path: only keys still for sale. It shrinks as the pool drains
-- and vanishes when it is empty — exactly when the claim query runs most often
-- and must not scan fifty dead rows. Indexing id gives the subquery's
-- ORDER BY id ... LIMIT 1 an ordered path instead of a sort.
CREATE INDEX "supplier_keys_unclaimed_idx" ON "supplier_keys" USING btree ("id") WHERE "claimed_by_request_id" IS NULL;
