-- ===========================================================================
-- 0006_promo_codes — the counter and the ledger (spec 005, "Promo codes with
-- enforced limits").
--
-- Generated by drizzle-kit from packages/db/src/schema/promo.ts and left
-- exactly as generated: two `CREATE TABLE`, two `ALTER TABLE ... ADD
-- CONSTRAINT ... FOREIGN KEY`, one `CREATE INDEX`, in the order drizzle-kit
-- emitted them. The only hand-edit is the annotations, in 0003's and 0005's
-- register, because this file — not the TypeScript — is what a reviewer who
-- does not know Drizzle reads. Strip every comment line, leave the statement
-- separators, and the bytes that remain are the generator's.
--
-- ONE TRAP FOR WHOEVER ANNOTATES THE NEXT FILE, found while writing this one:
-- the migrator splits a file on its statement separator AS A RAW SUBSTRING,
-- comments included. A comment that quotes the separator's text cuts itself
-- in two, and the tail — no longer behind a `--` — is sent to Postgres as
-- SQL. The whole migration transaction rolls back with a syntax error naming
-- the second half of your sentence. Describe the separator; do not spell it.
--
-- Two tables, two invariants from architecture.md §3:
--
--   I7  promo_codes.used_count ............ a promo is used at most N times
--   I8  promo_redemptions PRIMARY KEY ...... one redemption per order
--
-- WHAT THIS BUYS
--
-- Functional spec 005: four codes — WELCOME10, GG500, LIMIT3, ONCEONLY — each
-- with a limit, and the rule that the limit holds when twenty shoppers redeem
-- at the same instant across four API processes. This file is the storage
-- those guarantees are made of. Nothing consumes it yet: the seed is the next
-- task in this slice, the redemption transaction is slice 2, the four-process
-- proof is slice 3.
--
-- THE COUNTER IS THE THING I7 GUARDS, AND IT IS GUARDED BY ONE STATEMENT
--
--   UPDATE promo_codes SET used_count = used_count + 1
--   WHERE id = $1 AND used_count < max_uses
--   RETURNING used_count;
--   -- 1 row  => this transaction holds one of the N uses.
--   -- 0 rows => EXHAUSTED. Nothing has been written; the transaction commits
--   --           empty and the shopper is told the code is spent. 409.
--
-- Why that admits exactly `max_uses` transactions when twenty run at once in
-- four processes, under READ COMMITTED, which is this project's isolation level
-- by design: every UPDATE of the same `promo_codes` row queues on that row's
-- lock, and when each in turn obtains it Postgres re-evaluates the WHERE
-- against the row AS THE PREVIOUS TRANSACTION COMMITTED IT, not as it was first
-- read. The fourth in the queue sees `used_count = 3`, matches zero rows, and
-- returns nothing. There is no window between reading the count and writing
-- it, because reading and writing are one statement. A `SELECT used_count`
-- followed by `UPDATE ... SET used_count = $computed` has that window — and
-- passes every single-process test, because a `max: 1` pool serialises
-- transactions inside one instance (architecture §7: 20 distinct keys against
-- one process, 9 against four). The limit is therefore proven across four
-- processes only (technical-considerations R1).
--
-- WHY THE COUNTER IS A COLUMN AND NOT `count(*)` OVER THE LEDGER. I7 needs a
-- ROW TO LOCK. Twenty transactions that all want LIMIT3 queue on the one
-- `promo_codes` row; a count derived from `promo_redemptions` has no such row
-- and therefore no such queue — each transaction would count under its own
-- snapshot, see 2, and all twenty would insert. So the counter and the ledger
-- are two columns that MUST AGREE: in production `used_count` always equals
-- `count(*)` grouped by `promo_id`. A test may recompute one from the other.
-- Production never does.
--
-- THE CHECK IS A BACKSTOP, NOT THE MECHANISM — AND IT HIDES A BROKEN GUARD
--
--   CHECK (used_count >= 0 AND used_count <= max_uses)
--
-- turns "the guard cannot overshoot" into "provably does not", at the layer
-- that still holds when TypeScript is bypassed. But weaken the guard to an
-- unconditional `SET used_count = used_count + 1` and run twenty redemptions
-- of a three-use code across four processes: the fourth increment does not
-- produce `used_count = 4` — it trips this CHECK (`23514 check_violation`),
-- its transaction aborts, the API answers 500, and the counter reads 3. A test
-- that asserts only `used_count = 3` stays green with the mechanism gone. That
-- is Phase 2's lesson — a UNIQUE index masking a broken lock — wearing a CHECK
-- constraint (technical-considerations R2). Every proof of the limit asserts
-- the SHAPE of the refusals (exactly N x 200, the rest x 409 exhausted, ZERO
-- 5xx) and the ledger rows, and the counter only in addition.
--
-- MIGRATION SAFETY. Two `CREATE TABLE` on relations that have never existed:
-- nothing to scan, nothing to rewrite, nothing to backfill; eight CHECKs
-- validated against zero rows. The two `ADD CONSTRAINT ... FOREIGN KEY` are the
-- statements that touch something real: adding a FK takes `SHARE ROW
-- EXCLUSIVE` on the REFERENCED table — observed in `pg_locks` on `orders`
-- while this file ran inside an open transaction — which blocks writes to
-- `orders` for the statement's duration and blocks no reads. Measured on this
-- project's Postgres 16.11 container, three runs of the whole file inside a
-- rolled-back transaction, per statement:
--
--   CREATE TABLE promo_codes ............ 37.8 ms / 16.7 ms / 13.9 ms (first
--                                         run cold)
--   CREATE TABLE promo_redemptions ......  6.7 ms /  6.0 ms /  5.5 ms
--   ADD FK -> orders ....................  6.4 ms /  2.1 ms /  2.3 ms
--   ADD FK -> promo_codes ...............  2.0 ms /  1.6 ms /  0.8 ms
--   CREATE INDEX promo_id ...............  2.8 ms /  1.9 ms /  1.6 ms
--
-- Writes to `orders` wait at most a few milliseconds. Verified rather than
-- reasoned about: `pg_class.relfilenode` for `orders`, `products`,
-- `deliveries`, `payment_events`, `issuance_attempts`, `supplier_keys`,
-- `supplier_requests` and `supplier_behaviour` is identical before and after
-- this migration. Nothing that already held a row was rewritten.
--
-- ATOMICITY. drizzle-orm's pg migrator opens ONE transaction spanning every
-- pending file and every `drizzle.__drizzle_migrations` insert (0002 corrected
-- the record; 0003 and 0005 restate it). This is one file with nothing pending
-- beside it, so that behaviour is irrelevant here — stated so nobody goes
-- looking for the reason it is not discussed.
--
-- ORDERING — what is not free to move.
--
--   * This file depends on `orders` (0000_init): the first FK references it.
--     Satisfied by journal order and by nothing else.
--   * Within this file: both `CREATE TABLE` before either `ALTER TABLE`, and
--     `promo_codes` before the FK that references it. drizzle-kit emits
--     exactly that order. The `CREATE INDEX` last is presentational.
--
-- SEEDING is the next task: the four codes, `ON CONFLICT (code) DO UPDATE` on
-- the definition columns — `kind`, `value`, `currency`, `max_uses` — and NEVER
-- `used_count`. A re-seed must not reset a counter, for the reason it does not
-- reset a supplier knob (0003). Re-seeding `max_uses` BELOW the current count
-- trips the range CHECK and aborts the seed — loud, and correct.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- (1) promo_codes — the four definitions, and the counter.
--
-- Every column except `used_count` is a DEFINITION: written by the seed,
-- authoritative, re-seedable. `used_count` is STATE, written by the I7
-- statement in the header and by nothing else in production. It carries the
-- one DEFAULT in this file — `0` — because the seed must not write the column
-- at all, and "never used" is the only value a freshly defined code can
-- honestly hold.
--
-- `id` is `serial` — a plain `integer` identity, where the older shop tables
-- use `bigint` — because the ledger's `promo_id` is an `integer` and a foreign
-- key's two ends must be the same type. Four rows do not need 64 bits.
--
-- No column references a shop table, deliberately: a promo is a definition
-- with a counter, not a relation. Which order used which code is the ledger's
-- fact, and the ledger points HERE, never the other way round — as `orders`
-- records a `sku` and `products` knows nothing about orders.
--
-- The lookup that starts a redemption, for the record:
--
--   SELECT id, code, kind, value, currency, max_uses
--   FROM promo_codes WHERE code = $1;
--   -- 0 rows => UNKNOWN CODE. 422, decided before anything is written.
--   -- No FOR UPDATE: the definition read must not serialise twenty shoppers
--   -- behind one row. The I7 UPDATE is what serialises, and it serialises
--   -- only the increment.
--
-- WHY EVERY CHECK, in the order they appear:
--
--   promo_codes_code_key (UNIQUE)     the shopper's handle for a definition,
--                                     and the seed's ON CONFLICT target.
--   promo_codes_code_normalised       "stored upper-case" is an INVARIANT, so
--                                     a fixture typo (`limit3`) fails loud
--                                     instead of minting a fifth code that no
--                                     normalised lookup can ever find. `btrim`
--                                     because that is what `trim(x)` is.
--   promo_codes_kind_check            the two kinds the brief defines; the
--                                     list is generated from `promoKinds` in
--                                     promo.ts so the TypeScript union and the
--                                     constraint cannot drift.
--   promo_codes_value_positive        a discount of nothing is not a discount;
--                                     a negative one is a surcharge.
--   promo_codes_percent_bounded       a percent discount cannot exceed the
--                                     price. `amount` is bounded by the
--                                     arithmetic instead (`min(value, price)`),
--                                     hence the CHECK is conditional on kind.
--   promo_codes_currency_iff_amount   boolean equality: `currency` is present
--                                     EXACTLY when the value is money. An
--                                     `amount` code without a currency and a
--                                     `percent` code with one are both refused.
--                                     It exists so the arithmetic can never
--                                     subtract dollars from roubles.
--   promo_codes_max_uses_positive     a code usable zero times does not exist.
--   promo_codes_used_count_range      the backstop from the header. The lower
--                                     bound guards the harnesses' cleanup,
--                                     which decrements by exactly what it
--                                     deleted: an over-decrement raises here
--                                     instead of leaving a negative count for
--                                     the next baseline check to explain.
--
-- What a bypass looks like, for anyone reading a log:
--
--   23514 check_violation
--   new row for relation "promo_codes" violates check constraint
--     "promo_codes_code_normalised"
-- ---------------------------------------------------------------------------
CREATE TABLE "promo_codes" (
	"id" serial PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"kind" text NOT NULL,
	"value" integer NOT NULL,
	"currency" text,
	"max_uses" integer NOT NULL,
	"used_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "promo_codes_code_key" UNIQUE("code"),
	CONSTRAINT "promo_codes_code_normalised" CHECK ("code" = upper(btrim("code"))),
	CONSTRAINT "promo_codes_kind_check" CHECK ("kind" IN ('percent', 'amount')),
	CONSTRAINT "promo_codes_value_positive" CHECK ("value" > 0),
	CONSTRAINT "promo_codes_percent_bounded" CHECK ("kind" <> 'percent' OR "value" <= 100),
	CONSTRAINT "promo_codes_currency_iff_amount" CHECK (("kind" = 'amount') = ("currency" IS NOT NULL)),
	CONSTRAINT "promo_codes_max_uses_positive" CHECK ("max_uses" > 0),
	CONSTRAINT "promo_codes_used_count_range" CHECK ("used_count" >= 0 AND "used_count" <= "max_uses")
);
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- (2) promo_redemptions — the ledger: which order used which code, at what
-- list price, for how much off.
--
-- ###########################################################################
-- # PRIMARY KEY (order_id) IS I8 STRENGTHENED. ONE CODE PER ORDER — NOT ONE   #
-- # USE OF EACH CODE PER ORDER.                                              #
-- ###########################################################################
--
-- architecture.md §3 wrote I8 as `UNIQUE (promo_id, order_id)`, which would
-- have let two DIFFERENT codes land on one order — a second discount on an
-- already-discounted price. The functional spec's rule is one code per order,
-- so the key is `(order_id)` alone. The stronger key implies the weaker: a
-- table with at most one row per `order_id` has at most one row per
-- `(promo_id, order_id)`, so everything I8 was written to guarantee still
-- holds, and architecture.md is amended to match (technical-considerations §1
-- decision 3, §5 assumption 2). The primary key is also the order view's join
-- key — `LEFT JOIN promo_redemptions ON order_id = orders.id` is 1:0..1 by
-- construction, so the view can never multiply rows.
--
--   INSERT INTO promo_redemptions
--     (order_id, promo_id, list_amount_minor, discount_minor)
--   VALUES ($1, $2, $3, $4)
--   ON CONFLICT (order_id) DO NOTHING
--   RETURNING order_id;
--   -- 1 row  => the use is recorded; reprice the order and commit.
--   -- 0 rows => IMPOSSIBLE UNDER THE ORDER LOCK, and therefore a thrown
--   --           error, not an outcome. The redemption transaction holds
--   --           `SELECT ... FROM orders WHERE id = $1 FOR UPDATE` and read
--   --           this table under it before deciding to write, so a
--   --           conflicting row means the lock discipline was broken. The
--   --           throw rolls back the I7 increment that preceded it — the one
--   --           rollback path in that transaction — and is a 500.
--
-- Contrast `deliveries_order_id_key` (0000_init), where 0 rows is the EXPECTED
-- loser of a race and the caller keeps the existing row. Here the race is
-- settled one statement earlier, by the order lock; the constraint is the
-- proof that it was.
--
-- The two amounts are STORED, NOT DERIVED — "the record of what was paid does
-- not change after the fact" is a property of columns. `orders.amount_minor`
-- becomes the amount to pay; `list_amount_minor` here is the only place the
-- list price survives, and `discount_minor` is the APPLIED (clamped) discount,
-- so `list_amount_minor = orders.amount_minor + discount_minor` holds even when
-- an `amount` code exceeds the price and the order costs 0.
--
--   promo_redemptions_discount_range  never negative, never more than the
--                                     price. The application clamps; this
--                                     refuses a bypass.
-- ---------------------------------------------------------------------------
CREATE TABLE "promo_redemptions" (
	"order_id" text PRIMARY KEY NOT NULL,
	"promo_id" integer NOT NULL,
	"list_amount_minor" integer NOT NULL,
	"discount_minor" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promo_redemptions_discount_range" CHECK ("discount_minor" >= 0 AND "discount_minor" <= "list_amount_minor")
);
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- (3) The two foreign keys.
--
-- `order_id -> orders(id)` is a REAL foreign key, by the `deliveries` argument
-- (architecture §2, 0000_init): only code that has already locked and read the
-- order writes this row, so a dangling reference can only be a bug, and a bug
-- worth refusing at the door. The table that deliberately carries NO such key
-- is `payment_events`, whose rows may legitimately arrive before their order;
-- the contrast is the point, and this table is on the `deliveries` side of it.
--
-- `promo_id -> promo_codes(id)` binds a use to a definition. The seed's
-- `ON CONFLICT (code) DO UPDATE` never changes `id`, so a re-seed cannot orphan
-- a ledger row.
--
-- `ON DELETE no action` on both: nothing in this shop deletes an order or a
-- code, and the test harnesses delete redemptions BEFORE orders for exactly
-- this reason (technical-considerations §2.5).
-- ---------------------------------------------------------------------------
ALTER TABLE "promo_redemptions" ADD CONSTRAINT "promo_redemptions_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "promo_redemptions" ADD CONSTRAINT "promo_redemptions_promo_id_promo_codes_id_fk" FOREIGN KEY ("promo_id") REFERENCES "public"."promo_codes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- (4) The FK column's index — and the reconciliation's access path.
--
--   SELECT promo_id, count(*) FROM promo_redemptions GROUP BY promo_id;
--   -- the counter/ledger agreement a TEST may check; production never
--   -- recomputes `used_count` from it.
--
-- Also serves the harnesses' cleanup, which deletes this test's rows by
-- `order_id` (the PK) and decrements each code by exactly the number it
-- removed — never a global recompute, which would silently REPAIR any drift
-- between counter and ledger that the baseline assertion exists to catch.
--
-- `order_id` needs no index of its own: it is the primary key.
-- ---------------------------------------------------------------------------
CREATE INDEX "promo_redemptions_promo_id_idx" ON "promo_redemptions" USING btree ("promo_id");
